CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(255) NOT NULL UNIQUE,
    product_id       BIGINT       NOT NULL,
    quantity         INTEGER      NOT NULL,
    status           VARCHAR(30)  NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_product_id ON orders (product_id);
