services:
  postgres-catalog:
    image: postgres:18-alpine
    container_name: eurotransit-catalog-postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres-catalog-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog -d catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-inventory:
    image: postgres:18-alpine
    container_name: eurotransit-inventory-postgres
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
    ports:
      - "5433:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory -d inventory"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-catalog-data:
  postgres-inventory-data:
